### ISSUE TITLE
More data for test suite

### ISSUE THREAD

**Issue by blink1073** [metabolite-atlas/metatlas#7]
Supply more files for more comprehensive testing of the file conversion service.  Some will be meant to fail and some will be meant to succeed.  Tests that exceed the capabilities of metatlas schema will yield one type of error.  Files that are inappropriate for met atlas will yield a different error.

**Comment by benbowen** [comment]
I'll need some guidance how to write the tests, but for a start here are a bunch of files that cover most of the cases we will see:
1) wrong file format (the mzXML file).  This should fail because its the wrong format.
2) polarity switching
3) how numbers are stored (either as 32bit or 64bit IEEE-1394 or a mixture of the two).

All files are in my GDrive
/files_too_big_to_email/metatlas_test_data/

This file was taken on a Thermo QExcative.  Its polarity switching (every other scan is +/- polarity).  Its m/z values are stored as 64-bit numbers and its intensity values are stored as 32 bit numbers.
FileName QExactive_FastPolaritySwitching_Mixture_of_32_and_64_bit.mzML
https://drive.google.com/file/d/0BxH9TO4hK-nEekU0eU9PSWxMMDA/view?usp=sharing

QExactive_Targeted_MSMS_Pos.mzML
https://drive.google.com/file/d/0BxH9TO4hK-nEQ1ZxYmFVMzU4TVE/view?usp=sharing

QExactive 32bit, buts its an mzXML.  This one should fail because its NOT mzML.
QExactive_Wrong_FileFormat.mzXML
https://drive.google.com/file/d/0BxH9TO4hK-nEWXVwRGZWX0l0ZDA/view?usp=sharing

file taken on an Agilent 6550 QTOF its all MS1 and all the same polarity.  It was converted to mzML with msconvert storing intensity and m/z values as 64 bit encoded numbers:
Agilent_MS1_64bit_encoded.mzML
https://drive.google.com/file/d/0BxH9TO4hK-nEdTZfY21DcEc1Z2s/view?usp=sharing

**Comment by blink1073** [comment]
Thanks Ben, I'll write the tests, this helps give me a sense of what to expect.  I'll have to host these files on Dropbox since Google Docs will not directly download files larger than 24Mb.

**Comment by blink1073** [comment]
QExactive_FastPolaritySwitching_Mixture_of_32_and_64_bit.mzML:

![figure_1](https://cloud.githubusercontent.com/assets/2096628/7265737/51c90bec-e864-11e4-9d59-19c74e41b70c.png)

**Comment by blink1073** [comment]
QExactive_Targeted_MSMS_Pos.mzML (I had to set precursor_intensity to NAN since no matching keys were found):

![figure_1](https://cloud.githubusercontent.com/assets/2096628/7265843/f20d422a-e865-11e4-8fb0-c513a22c9143.png)

**Comment by blink1073** [comment]
Yikes, the Agilent file is *huge*.  Do you have a smaller one?  This sucker would take up most of our unit test time.

**Comment by blink1073** [comment]
How's this traceback:

```python
$ python mzml_loader.py -i test.mzXML
Traceback (most recent call last):
  File "mzml_loader.py", line 56, in mzml_to_hdf
    extraAccessions=extraAccessions)
  File "/Users/silvester/anaconda/lib/python3.4/site-packages/pymzml/run.py", line 238, in __init__
    event, element = next(self.iter)
  File "/Users/silvester/anaconda/lib/python3.4/xml/etree/ElementTree.py", line 1300, in __next__
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mzml_loader.py", line 151, in <module>
    main()
  File "mzml_loader.py", line 147, in main
    mzml_to_hdf(args.input, args.output, args.debug)
  File "mzml_loader.py", line 58, in mzml_to_hdf
    raise TypeError('Not a valid mzML file: %s' % in_file_name)
TypeError: Not a valid mzML file: test.mzXML
```

**Comment by blink1073** [comment]
And finally, Agilent_MS1_64bit_encoded.mzML:

![figure_1](https://cloud.githubusercontent.com/assets/2096628/7266114/8d25d070-e86a-11e4-80ef-ed7a910c5d5b.png)

**Comment by benbowen** [comment]
Can you remove the agilent file from testing?  I'm really happy that it
passed.  That means that we can use 64-bit encoded values.  Last year there
was something broken with the xml parser that blocked this.  I have some
tiny Agilent files on server, but will have to dig them up.  For now, just
remove the beast.  I think we are good to go.

--------------
Email: BPBowen@lbl.gov
Google Voice: (510) 214-6683
Mobile: (480) 225-2341
MS 977-221, Lawrence Berkeley Lab
OpenMSI: http://openmsi.nersc.gov

**Comment by blink1073** [comment]
I haven't fully added these to the test suite yet.

**Comment by blink1073** [comment]
Note that I am still storing alp values as 32bit floats regardless of original encoding.  They are read out from the mzML file as Python floats.

**Comment by benbowen** [comment]
Thats fine with me.  Its the converters we have to use to print the
vendor's proprietary file formats as XML.  They default to using 64-bit
encoded IEEE-1394 values, and some of the XML parsers don't support
64-bit.  I guess with whatever updates to the XML parser it got built in.

--------------
Email: BPBowen@lbl.gov
Google Voice: (510) 214-6683
Mobile: (480) 225-2341
MS 977-221, Lawrence Berkeley Lab
OpenMSI: http://openmsi.nersc.gov

**Comment by benbowen** [comment]
Ben needs to find a profile mode file.  We should flag this at upload and not import it until the storage capabilities can support it.

**Comment by benbowen** [comment]
Seems like small profile mode files would be ok to load.  I think we should be able to support large files.  They will take a long time to convert, but that's ok as long as they don't go into memory during load.
